#!/usr/bin/env sh

monitors={eDP-1-1,HDMI-1-1}

#
# wm independent hotkeys
#

alt + Return
	$TERMINAL

alt + b
	$BROWSER

alt + r
	$TERMINAL -e ranger

alt + f
    $TERMINAL -e lf

alt + m
	$TERMINAL -e cmus

alt + s
    tdrop -ma -w -4 alacritty

alt + @space
	rofi -show drun

alt + shift + @space
	rofi -show run

alt + Escape
	pkill -USR1 -x sxhkd

alt + End
	poweroff

alt + Next
    xsecurelock

#
# bspwm hotkeys
#

# quit/restart bspwm
super + {q,r}
	bspc {quit,wm -r}

# close and kill
alt + {_,shift + }q
	bspc node -{c,k}

# alternate between the tiled and monocle layout
alt + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
alt + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
alt + g
	bspc node -s biggest

#
# state/flags
#

# set the window state
alt + {t,shift + t,shift + s,shift + f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
alt + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
alt + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
alt + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
alt + {_,shift + }c
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
alt + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
alt + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
alt + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
alt + {_,shift + }{1-9,0}
    bspc {desktop -f,node -d} '^{1-9,10}'

# SEND TO MONITOR
alt + bracket{left,right}
    bspc monitor -f {HDMI-1-1,eDP-1-1}

alt + shift + bracket{left,right}
    bspc node --to-monitor {HDMI-1-1,eDP-1-1}





#
# preselect
#

# preselect the direction
alt + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
alt + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
alt + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
alt + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
ctrl + alt + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
ctrl + alt + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
alt + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}


# MULTIMIDIA

XF86AudioRaiseVolume
	pamixer -i 10

XF86AudioLowerVolume
	pamixer -d 10

XF86AudioMute
	pamixer -t

XF86MonBrightnessUp
	light -A 5

XF86MonBrightnessDown
	light -U 5

XF86TouchpadToggle
	/some/path/toggletouchpad.sh # toggle touchpad

XF86AudioPlay
	playerclt play

XF86AudioPause
	playerctl pause

XF86AudioNext
	playerctl next

XF86AudioPrev
	playerctl previous

