#!/bin/sh


# MONITORS
bspc monitor -d 1 2 3 4 5 6 7 8 9 10


unfocused=#3B4252
focused=#D8DEE9
select=#B48EAD
padding=0

for side in top right bottom left; do
	bspc config ${side}_padding $padding
done

bspc config normal_border_color			$unfocused
bspc config active_border_color			$unfocused
bspc config focused_border_color		$focused
bspc config presel_feedback_color		$select
bspc config border_width    		    2
bspc config window_gap          		0
bspc config split_ratio          		0.5
bspc config borderless_monocle   		true
bspc config gapless_monocle      		true
bspc config paddingless_monocle			true
bspc config single_monocle				false
bspc config focus_follows_pointer		false


# RULES
bspc rule -a qutebrowser desktop=^3
bspc rule -a firefoxdeveloperedition desktop=^3
bspc rule -a "Gimp-2.10:gimp-2.10" desktop=^4 follow=on
bspc rule -a Inkscape desktop=^4
bspc rule -a krita desktop=^4
bspc rule -a "TelegramDesktop:telegram-desktop-bin" desktop=^5
bspc rule -a discord desktop=^5
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a Zathura state=fullscreen



# FIX JAVA APPLICATIONS COMPACTIBILITY
wmname LG3D &
