#! /bin/sh


bspc monitor HDMI-1-1 -d I II III IV V VI VII VIII IX X
# bspc monitor -d I II III IV V VI VII VIII IX X


unfocused=#3A2F3F
focused=#FF3CFF
select=#FF3CFF
padding=0

for side in top right bottom left; do
	bspc config ${side}_padding $padding
done

bspc config normal_border_color			$unfocused
bspc config active_border_color			$unfocused
bspc config focused_border_color		$focused
bspc config presel_feedback_color		$select
bspc config border_width    		    2
bspc config window_gap          		0
bspc config split_ratio          		0.5
bspc config borderless_monocle   		true
bspc config gapless_monocle      		true
bspc config focus_follows_pointer		true
bspc config paddingless_monocle			true
bspc config single_monocle				false


# RULES
bspc rule -a Gimp desktop='^3' state=floating follow=on
bspc rule -a qutebrowser desktop='^2'
bspc rule -a Spotify:spotify desktop='^5'


# AUTOSTART
sxhkd &
feh --bg-scale ~/Pictures/Wallpapers/japan-purple.jpg &
$HOME/.config/polybar/launch.sh &
setxkbmap br &
dunst &
nm-applet &
fcitx &
compton -b &
blueman-applet &
redshift-gtk &


