#!/bin/sh


# MONITORS
bspc monitor -d I II III IV V VI VII VIII IX X


unfocused=#3A2F3F
focused=#FF3CFF
select=#FF3CFF
padding=0

for side in top right bottom left; do
	bspc config ${side}_padding $padding
done

bspc config normal_border_color			$unfocused
bspc config active_border_color			$unfocused
bspc config focused_border_color		$focused
bspc config presel_feedback_color		$select
bspc config border_width    		    2
bspc config window_gap          		0
bspc config split_ratio          		0.5
bspc config borderless_monocle   		true
bspc config gapless_monocle      		true
bspc config focus_follows_pointer		true
bspc config paddingless_monocle			true
bspc config single_monocle				false


# RULES
bspc rule -a Nightly desktop=^2
bspc rule -a firefox desktop=^2
bspc rule -a firefoxdeveloperedition desktop=^2
bspc rule -a qutebrowser desktop=^2

bspc rule -a dolphin desktop=^4

bspc rule -a "Gimp-2.10:gimp-2.10" desktop=^4 follow=on
bspc rule -a Inkscape desktop=^4
bspc rule -a krita desktop=^4

bspc rule -a "TelegramDesktop:telegram-desktop" desktop=^5
bspc rule -a discord desktop=^5

bspc rule -a Spotify desktop=^6
bspc rule -a spotify desktop=^6

bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled


# FIX JAVA WM COMPACTIBILITY
wmname LG3D &
