#!/usr/bin/env sh


super + Return
	$TERMINAL
super + shift + Return
    samedir
super + b
	$BROWSER
super + alt + f
    $TERMINAL -e lf
super + c
    $TERMINAL -e calcurse
super + m
	$TERMINAL -e cmus
super + v
	$TERMINAL -e pulsemixer
super + s
    tdrop -ma -w -4 alacritty
super + @space
	rofi -show drun
super + shift + @space
	rofi -show run
super + Escape
	pkill -USR1 -x sxhkd
super + End
    doas poweroff
super + Home
    loginctl suspend
super + Next
    xsecurelock
super + alt + h
    zathura ~/Documents/HORARIO_DE_AULA.pdf
Print
    maim ~/Pictures/Screenshots/$(date '+%y%m%d-%H%M-%S').png
# Pick screenshot type
shift + Print
    maim -i $(xdotool getactivewindow) | xclip -selection clipboard -t image/png
super + alt + t
    telegram-desktop

#
# bspwm hotkeys
#

# quit/restart bspwm
super + alt + {q,r}
	bspc {quit,wm -r}

# close and kill
super + {_,shift + }q
	bspc node -{c,k}

# alternate between the tiled and monocle layout
super + shift + m
	bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
	bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + g
	bspc node -s biggest

#
# state/flags
#

# set the window state
super + {t,shift + t,shift + s,f}
	bspc node -t {tiled,pseudo_tiled,floating,fullscreen}

# set the node flags
super + ctrl + {m,x,y,z}
	bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{h,j,k,l}
	bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
super + shift + {p,b,comma,period}
	bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }r
	bspc node -f {next,prev}.local

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
	bspc desktop -f {prev,next}.local

# focus the last node/desktop
super + {grave,Tab}
	bspc {node,desktop} -f last

# focus the older or newer node in the focus history
super + {o,i}
	bspc wm -h off; \
	bspc node {older,newer} -f; \
	bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
    bspc {desktop -f,node -d} '^{1-9,10}'

# SEND TO MONITOR
super + bracket{left,right}
    bspc monitor -f {HDMI-1-1,eDP-1-1}

super + shift + bracket{left,right}
    bspc node --to-monitor {HDMI-1-1,eDP-1-1}

#
# preselect
#

# preselect the direction
alt + ctrl + {h,j,k,l}
	bspc node -p {west,south,north,east}

# preselect the ratio
alt + ctrl + {1-9}
	bspc node -o 0.{1-9}

# cancel the preselection for the focused node
alt + ctrl + space
	bspc node -p cancel

# cancel the preselection for the focused desktop
alt + ctrl + shift + space
	bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# expand a window by moving one of its side outward
ctrl + super + {h,j,k,l}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
ctrl + super + shift + {h,j,k,l}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
	bspc node -v {-20 0,0 20,0 -20,20 0}


# MULTIMIDIA

XF86AudioRaiseVolume
    pulsemixer --change-volume +5
    #amixer -q sset Master 5%+
XF86AudioLowerVolume
    pulsemixer --change-volume -5
    #amixer -q sset Master 5%-
XF86AudioMute
    pulsemixer --toggle-mute
    #amixer -q sset Master toggle
XF86MonBrightnessUp
	light -A 5
XF86MonBrightnessDown
	light -U 5
XF86TouchpadToggle
	/some/path/toggletouchpad.sh # toggle touchpad
XF86AudioPlay
	playerclt play
XF86AudioPause
	playerctl pause
XF86AudioNext
	playerctl next
XF86AudioPrev
	playerctl previous
