#! /bin/sh

sxhkd &
feh --bg-scale ~/Pictures/Wallpapers/japan-purple.jpg &
$HOME/.config/polybar/launch.sh &

setxkbmap br

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^2'
bspc rule -a Spotify desktop='^5'

