#!/bin/sh
alias \
    e="ls -hN --color=auto --group-directories-first" \
    ea="ls -lahN --color=auto --group-directories-first" \
    v="$EDITOR" \
    vi="$EDITOR" \
    vf='$EDITOR "$(fzf)"' \
    vo='$TERMINAL -e $EDITOR "$(fzf)"' \
    dvi="doas $EDITOR" \
    py="python3" \
    g="git" \
    gs="git status" \
    gb="git branch" \
    gc='git commit' \
    gch="git checkout" \
    ga="git add" \
    gd="git diff" \
    gl="git log" \
    xi="doas xbps-install -S" \
    xu="doas xbps-install -Su" \
    xr="doas xbps-remove -R" \
    xq="xbps-query -Rs" \
    yt="youtube-dl --add-metadata -i" \
    yta="yt -x -f bestaudio/best" \
    ytm="yt -x -f 251 --add-metadata " \

# Open coniguration files
alias \
    cfp="$EDITOR ~/.profile" \
    cfa="$EDITOR ~/.config/aliasrc" \
    cfz="$EDITOR ~/.config/zathura/zathurarc" \
    cfi3="$EDITOR ~/.config/i3/config" \
    cfbar="$EDITOR ~/.config/polybar/config" \
    cfnvim="$EDITOR ~/.config/nvim/init.vim" \
    cfvis="$EDITOR ~/.config/vis/visrc.lua" \
    cfterm="$EDITOR ~/.config/alacritty/alacritty.yml" \
    cfwm="$EDITOR ~/.config/bspwm/bspwmrc" \
    cfk="$EDITOR ~/.config/sxhkd/sxhkdrc" \
    cfsway="$EDITOR ~/.config/sway/config" \
    cflf="$EDITOR ~/.config/lf/lfrc" \
    cfqb="$EDITOR ~/.config/qutebrowser/config.py" \
    cfgrub="doas $EDITOR /etc/default/grub" \
