abbr vi	    "nvim"
abbr svi    "sudo nvim"
abbr vf    "nvim (fzf)"
abbr py     "python3"

abbr g      "git"
abbr gs     "git status"
abbr gb     "git branch"
abbr gc     'git commit'
abbr gch    "git checkout"
abbr ga     "git add"
abbr gd     "git diff"
abbr gl     "git log"

abbr xi     "sudo xbps-install -Su"
abbr xr     "sudo xbps-remove -R"
abbr xq     "xbps-query -Rs"

# OPEN CONIGURATION FILES
abbr cfi3 	"nvim ~/.config/i3/config"
abbr cfbar 	"nvim ~/.config/polybar/config"
abbr cff	"nvim ~/.config/fish/config.fish"
abbr cfabbr	"nvim ~/.config/fish/abbreviations.fish"
abbr cfpfl	"nvim ~/.config/fish/profile"
abbr cfvi 	"nvim ~/.config/nvim/init.vim"
abbr cfterm	"nvim ~/.config/alacritty/alacritty.yml"
abbr cfwm 	"nvim ~/.config/bspwm/bspwmrc"
abbr cfk 	"nvim ~/.config/sxhkd/sxhkdrc"
abbr cfr 	"nvim ~/.config/rofi/config"
abbr cflf 	"nvim ~/.config/lf/lfrc"
abbr cfqb 	"nvim ~/.config/qutebrowser/config.py"
